security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        customer_provider:
            entity:
                class: App\Entity\Customer
                property: email
        seller_provider:
            entity:
                class: App\Entity\Seller
                property: email
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        admin:
            pattern: ^/admin
            context: admin_context
            provider: admin_provider
            user_checker: App\Security\AdminUserChecker
            lazy: true
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: app_admin_dashboard
                enable_csrf: true
            logout:
                path: admin_logout
                target: admin_login

        seller:
            pattern: ^/seller
            context: seller_context
            provider: seller_provider
            user_checker: App\Security\SellerUserChecker
            lazy: true
            form_login:
                login_path: seller_login
                check_path: seller_login
                default_target_path: app_seller_dashboard
                enable_csrf: true
            logout:
                path: seller_logout
                target: seller_login

        main:
            lazy: true
            context: customer_context
            provider: customer_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/invite, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/seller/login, roles: PUBLIC_ACCESS }
        - { path: ^/seller/activate, roles: PUBLIC_ACCESS }
        - { path: ^/become-seller, roles: ROLE_CUSTOMER }
        - { path: ^/seller, roles: ROLE_SELLER }
        - { path: ^/profile, roles: ROLE_CUSTOMER }
        - { path: ^/orders, roles: ROLE_CUSTOMER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
