<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260708120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Split user into customer/admin/seller entities with profiles and seller requests.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "user" RENAME TO customer');
        $this->addSql('ALTER INDEX uniq_identifier_email RENAME TO uniq_customer_email');

        $this->addSql('CREATE TABLE customer_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_id INT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DE3690C9395C3F3 ON customer_profile (customer_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DE3690C444F97DD ON customer_profile (phone)');
        $this->addSql('ALTER TABLE customer_profile ADD CONSTRAINT FK_2DE3690C9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('INSERT INTO customer_profile (customer_id, first_name, last_name, phone) SELECT id, first_name, last_name, phone FROM customer');
        $this->addSql('ALTER TABLE customer DROP first_name');
        $this->addSql('ALTER TABLE customer DROP last_name');
        $this->addSql('ALTER TABLE customer DROP phone');

        $this->addSql("UPDATE customer SET roles = REPLACE(roles::text, 'ROLE_USER', 'ROLE_CUSTOMER')::json");

        $this->addSql('CREATE TABLE admin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_admin_email ON admin (email)');

        $this->addSql('CREATE TABLE admin_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, admin_id INT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_403D9ED3642B8210 ON admin_profile (admin_id)');
        $this->addSql('ALTER TABLE admin_profile ADD CONSTRAINT FK_403D9ED3642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE admin_invite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by_id INT DEFAULT NULL, token VARCHAR(64) NOT NULL, email VARCHAR(180) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_admin_invite_token ON admin_invite (token)');
        $this->addSql('CREATE INDEX IDX_4BDE4B4EB03A8386 ON admin_invite (created_by_id)');
        $this->addSql('ALTER TABLE admin_invite ADD CONSTRAINT FK_4BDE4B4EB03A8386 FOREIGN KEY (created_by_id) REFERENCES admin (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE seller (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_id INT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, activation_token VARCHAR(64) DEFAULT NULL, activation_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_seller_email ON seller (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_seller_customer ON seller (customer_id)');
        $this->addSql('CREATE INDEX IDX_FB1AD3FC9395C3F3 ON seller (customer_id)');
        $this->addSql('ALTER TABLE seller ADD CONSTRAINT FK_FB1AD3FC9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE seller_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, seller_id INT NOT NULL, shop_name VARCHAR(255) NOT NULL, legal_name VARCHAR(255) DEFAULT NULL, inn VARCHAR(12) DEFAULT NULL, description TEXT DEFAULT NULL, contact_phone VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B9A1F628DE820D9 ON seller_profile (seller_id)');
        $this->addSql('ALTER TABLE seller_profile ADD CONSTRAINT FK_4B9A1F628DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE seller_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, seller_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, status VARCHAR(16) NOT NULL, shop_name VARCHAR(255) NOT NULL, legal_name VARCHAR(255) DEFAULT NULL, inn VARCHAR(12) DEFAULT NULL, description TEXT DEFAULT NULL, contact_phone VARCHAR(255) DEFAULT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rejection_reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E9F97018DE820D9 ON seller_request (seller_id)');
        $this->addSql('CREATE INDEX IDX_3E9F9701FC6B21F1 ON seller_request (reviewed_by_id)');
        $this->addSql('ALTER TABLE seller_request ADD CONSTRAINT FK_3E9F97018DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seller_request ADD CONSTRAINT FK_3E9F9701FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES admin (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE export_file DROP CONSTRAINT FK_4D6B2F48D9F6D38');
        $this->addSql('UPDATE export_file SET requested_by_id = NULL');
        $this->addSql('ALTER TABLE export_file ADD CONSTRAINT FK_4D6B2F48D9F6D38 FOREIGN KEY (requested_by_id) REFERENCES admin (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE export_file DROP CONSTRAINT FK_4D6B2F48D9F6D38');
        $this->addSql('UPDATE export_file SET requested_by_id = NULL');
        $this->addSql('ALTER TABLE export_file ADD CONSTRAINT FK_4D6B2F48D9F6D38 FOREIGN KEY (requested_by_id) REFERENCES customer (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE seller_request DROP CONSTRAINT FK_3E9F9701FC6B21F1');
        $this->addSql('ALTER TABLE seller_request DROP CONSTRAINT FK_3E9F97018DE820D9');
        $this->addSql('DROP TABLE seller_request');
        $this->addSql('ALTER TABLE seller_profile DROP CONSTRAINT FK_4B9A1F628DE820D9');
        $this->addSql('DROP TABLE seller_profile');
        $this->addSql('ALTER TABLE seller DROP CONSTRAINT FK_FB1AD3FC9395C3F3');
        $this->addSql('DROP TABLE seller');
        $this->addSql('ALTER TABLE admin_invite DROP CONSTRAINT FK_4BDE4B4EB03A8386');
        $this->addSql('DROP TABLE admin_invite');
        $this->addSql('ALTER TABLE admin_profile DROP CONSTRAINT FK_403D9ED3642B8210');
        $this->addSql('DROP TABLE admin_profile');
        $this->addSql('DROP TABLE admin');

        $this->addSql('ALTER TABLE customer ADD first_name VARCHAR(255) NOT NULL DEFAULT \'\'');
        $this->addSql('ALTER TABLE customer ADD last_name VARCHAR(255) NOT NULL DEFAULT \'\'');
        $this->addSql('ALTER TABLE customer ADD phone VARCHAR(255) NOT NULL DEFAULT \'\'');
        $this->addSql('UPDATE customer c SET first_name = p.first_name, last_name = p.last_name, phone = p.phone FROM customer_profile p WHERE p.customer_id = c.id');
        $this->addSql('ALTER TABLE customer_profile DROP CONSTRAINT FK_2DE3690C9395C3F3');
        $this->addSql('DROP TABLE customer_profile');

        $this->addSql("UPDATE customer SET roles = REPLACE(roles::text, 'ROLE_CUSTOMER', 'ROLE_USER')::json");
        $this->addSql('ALTER INDEX uniq_customer_email RENAME TO uniq_identifier_email');
        $this->addSql('ALTER TABLE customer RENAME TO "user"');
    }
}
