<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260625125500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create job and export_file tables for background process tracking.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_id VARCHAR(32) NOT NULL, type VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_job_job_id ON job (job_id)');
        $this->addSql('CREATE INDEX idx_job_status ON job (status)');
        $this->addSql('CREATE INDEX idx_job_created_at ON job (created_at)');
        $this->addSql('CREATE TABLE export_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_id INT DEFAULT NULL, requested_by_id INT DEFAULT NULL, export_id VARCHAR(32) NOT NULL, resource VARCHAR(64) NOT NULL, format VARCHAR(16) NOT NULL, filters JSON NOT NULL, storage VARCHAR(32) DEFAULT NULL, file_path VARCHAR(512) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_export_file_export_id ON export_file (export_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D6B2F4ABE04EA9 ON export_file (job_id)');
        $this->addSql('CREATE INDEX IDX_4D6B2F48D9F6D38 ON export_file (requested_by_id)');
        $this->addSql('ALTER TABLE export_file ADD CONSTRAINT FK_4D6B2F4ABE04EA9 FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE export_file ADD CONSTRAINT FK_4D6B2F48D9F6D38 FOREIGN KEY (requested_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE export_file DROP CONSTRAINT FK_4D6B2F4ABE04EA9');
        $this->addSql('ALTER TABLE export_file DROP CONSTRAINT FK_4D6B2F48D9F6D38');
        $this->addSql('DROP TABLE export_file');
        $this->addSql('DROP TABLE job');
    }
}
