# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator $customerFormLoginAuthenticator: '@security.authenticator.form_login.main'
            Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator $adminFormLoginAuthenticator: '@security.authenticator.form_login.admin'
            Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator $sellerFormLoginAuthenticator: '@security.authenticator.form_login.seller'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        App\Export\Contract\ExportDataProviderInterface:
            tags: [ 'app.export.data_provider' ]
        App\Export\Contract\ExportWriterInterface:
            tags: [ 'app.export.writer' ]
        App\Export\Contract\ExportCriteriaFactoryInterface:
            tags: [ 'app.export.criteria_factory' ]

    App\Service\Export\ExportService:
        arguments:
            $dataProviders: !tagged_iterator app.export.data_provider
            $writers: !tagged_iterator app.export.writer

    App\Resolver\Export\ExportCriteriaResolver:
        arguments:
            $factories: !tagged_iterator app.export.criteria_factory

    App\MessageHandler\ExportHandler:
        arguments:
            $projectDir: '%kernel.project_dir%'
